# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  pipelinePath : 'resturnat/pipelines'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub SC'
          command: 'login'
        displayName: 'Docker login'
      - task: Docker@2
        inputs:
            containerRegistry: 'Docker Hub SC'
            repository: 'amryoussef93 / asp-net-devops-demo'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
        displayName: 'Docker build and push to docker hub'
      - task: PublishPipelineArtifact@1 
        displayName: 'publish artifacts'
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)'
          artifact: 'resturnat'
          publishLocation: 'pipeline'
      - task: DownloadPipelineArtifact@2
        displayName: 'download artifacts'
        inputs:
          buildType: 'current'
          artifactName: 'resturnat'
          targetPath: '$(Pipeline.Workspace)'

- stage: Deploy
  dependsOn: Build
  displayName: Deploy To K8s
  jobs:
  - job: Deploy
    steps:
       - task: DownloadPipelineArtifact@2
         displayName: 'download artifacts'
         inputs:
          buildType: 'current'
          artifactName: 'resturnat'
          targetPath: '$(Pipeline.Workspace)'

      #  - task: KubernetesManifest@0
      #    displayName: 'Create Secters'
      #    inputs:
      #     action: 'createSecret'
      #     kubernetesServiceConnection: 'restk8sSC'
      #     secretType: 'dockerRegistry'
      #     secretName: 'dckrHub'
      #     dockerRegistryEndpoint: 'Docker Hub SC'

       - task: KubernetesManifest@0
         displayName: 'Deploy to k8s'
         inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'restk8sSC'
            manifests: |
               $(Pipeline.Workspace)/resturnat/pipelines/deployment.yml
               $(Pipeline.Workspace)/resturnat/pipelines/service.yml
            imagePullSecrets: 'dckrHub'


      #  - task: KubernetesManifest@0
      #    displayName: Deploy
      #    inputs:
      #      action: 'deploy'
      #      kubernetesServiceConnection: 'restk8sSC'
      #      namespace: 'default'
      #      manifests: | 
      #        $(pipelinePath)/deployment.yml
      #        $(pipelinePath)/service.yml'
      #      containers: ''
      #      imagePullSecrets: ''
      #  - task: KubernetesManifest@0
      #    inputs:
      #     action: 'createSecret'
      #     kubernetesServiceConnection: 'restk8sSC'
      #     secretType: 'dockerRegistry'
      #     secretName: 'dockerhb'
      #     dockerRegistryEndpoint: 'Docker Hub SC'
      
  