# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub SC'
          command: 'login'
        displayName: 'Docker login'
      - task: Docker@2
        inputs:
            containerRegistry: 'Docker Hub SC'
            repository: 'amryoussef93 / asp-net-devops-demo'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
        displayName: 'Docker build and push to docker hub'

- stage: Deploy
  dependsOn: Build
  displayName: Deploy To K8s
  jobs:
  - job: Deploy
    steps:
       - task: KubernetesManifest@0
         displayName: Deploy
         inputs:
           action: 'deploy'
           kubernetesServiceConnection: 'restk8sSC'
           namespace: 'default'
           manifests: | 
             pipelines/deployment.yml
             manifests/service.yml'
           containers: ''
           imagePullSecrets: ''
  