apiVersion : apps/v1
kind: Deployment
metadata:
  name: resturantapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resturantapp
  template:
    metadata:
      labels:
        app: resturantapp 
    spec:
      containers:
        - name: resturantapp 
          image: amryoussef93/asp-net-devops-demo
          ports:
          - containerPort: 80